//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G4_SC601_KN_Proyecto.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class auditoria
    {
        public int id_auditoria { get; set; }
        public int id_usuario { get; set; }
        public string accion { get; set; }
        public string tabla_afectada { get; set; }
        public System.DateTime fecha { get; set; }
        public string detalles { get; set; }
    
        public virtual usuario usuario { get; set; }
    }
}
