//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G4_SC601_KN_Proyecto.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class bitacora_errores
    {
        public int id_error { get; set; }
        public string mensaje_error { get; set; }
        public string stack_trace { get; set; }
        public string contexto { get; set; }
        public Nullable<System.DateTime> fecha_hora { get; set; }
        public string usuario { get; set; }
    }
}
