//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G4_SC601_KN_Proyecto.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class lote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public lote()
        {
            this.movimiento_inventario = new HashSet<movimiento_inventario>();
            this.stock = new HashSet<stock>();
        }
    
        public int id_lote { get; set; }
        public int id_material { get; set; }
        public string codigo_lote { get; set; }
        public System.DateTime fecha_vencimiento { get; set; }
        public System.DateTime fecha_ingreso { get; set; }
    
        public virtual material material { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<movimiento_inventario> movimiento_inventario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stock> stock { get; set; }
    }
}
