//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G4_SC601_KN_Proyecto.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SC604Proyecto_DBEntities : DbContext
    {
        public SC604Proyecto_DBEntities()
            : base("name=SC604Proyecto_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<auditoria> auditoria { get; set; }
        public virtual DbSet<bodega> bodega { get; set; }
        public virtual DbSet<categoria> categoria { get; set; }
        public virtual DbSet<errores> errores { get; set; }
        public virtual DbSet<lote> lote { get; set; }
        public virtual DbSet<movimiento_inventario> movimiento_inventario { get; set; }
        public virtual DbSet<pasillo> pasillo { get; set; }
        public virtual DbSet<producto> producto { get; set; }
        public virtual DbSet<rack> rack { get; set; }
        public virtual DbSet<registro_error> registro_error { get; set; }
        public virtual DbSet<rol> rol { get; set; }
        public virtual DbSet<ruta> ruta { get; set; }
        public virtual DbSet<stock> stock { get; set; }
        public virtual DbSet<ubicacion> ubicacion { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
