//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G4_SC601_KN_Proyecto.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SC604Proyecto_DBEntities : DbContext
    {
        public SC604Proyecto_DBEntities()
            : base("name=SC604Proyecto_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<auditoria> auditoria { get; set; }
        public virtual DbSet<bitacora_errores> bitacora_errores { get; set; }
        public virtual DbSet<errores> errores { get; set; }
        public virtual DbSet<family> family { get; set; }
        public virtual DbSet<lote> lote { get; set; }
        public virtual DbSet<material> material { get; set; }
        public virtual DbSet<movimiento_inventario> movimiento_inventario { get; set; }
        public virtual DbSet<parent> parent { get; set; }
        public virtual DbSet<rol> rol { get; set; }
        public virtual DbSet<stock> stock { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<ubicacion> ubicacion { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
