//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G4_SC601_KN_Proyecto.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class movimiento_inventario
    {
        public int id_movimiento { get; set; }
        public int id_material { get; set; }
        public Nullable<int> id_lote { get; set; }
        public int id_ubicacion { get; set; }
        public string tipo { get; set; }
        public int cantidad { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public int id_usuario { get; set; }
    
        public virtual lote lote { get; set; }
        public virtual material material { get; set; }
        public virtual ubicacion ubicacion { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
