//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G4_SC601_KN_Proyecto.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usuario()
        {
            this.auditoria = new HashSet<auditoria>();
            this.movimiento_inventario = new HashSet<movimiento_inventario>();
        }
    
        public int id_usuario { get; set; }
        public string nombre { get; set; }
        public string apellido_1 { get; set; }
        public string usuario1 { get; set; }
        public string email { get; set; }
        public string contrasena { get; set; }
        public int id_rol { get; set; }
        public int intentos_fallidos { get; set; }
        public bool bloqueado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<auditoria> auditoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<movimiento_inventario> movimiento_inventario { get; set; }
        public virtual rol rol { get; set; }
    }
}
